# Generated by Django 4.2.5 on 2023-09-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Учебный центр',
                'verbose_name_plural': 'Учебные центры',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О преподавателе')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Опыт')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studycenter')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О студенте')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studycenter')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
